services:
  plateform-test:
    build:
      context: .
      dockerfile: dockerfile
    image: plateform-test:latest
    container_name: plateform-test
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    expose:
      - "3000"
